DROP SCHEMA IF EXISTS dnd CASCADE;
CREATE SCHEMA dnd;

-- Пользователи и роли
CREATE TABLE dnd.user_role (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE dnd."user" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_role_id INTEGER NOT NULL REFERENCES dnd.user_role(id),
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    avatar_url VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dnd.user_auth (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES dnd."user"(id) ON DELETE CASCADE,
    provider VARCHAR(50) NOT NULL,
    provider_user_id VARCHAR(255),
    password_hash VARCHAR(255),
    access_token TEXT,
    refresh_token TEXT,
    token_expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, provider)
);

-- Справочники игровых сущностей
CREATE TABLE dnd.item_category (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE dnd.pool (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description text
);

CREATE TABLE dnd.note (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL UNIQUE,
    content TEXT
);

CREATE TABLE dnd.ability_type (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE dnd.ability (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    ability_type_id INTEGER NOT NULL REFERENCES dnd.ability_type(id),
    description TEXT   -- сюда же теперь вписывается урон, эффекты, условия
);

CREATE TABLE dnd.class (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE dnd.branch (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id INTEGER REFERENCES dnd.class(id),
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE dnd.species (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE dnd.inventory (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    max_weight DECIMAL NOT NULL
);

CREATE TABLE dnd.stat (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id INTEGER REFERENCES dnd.class(id),
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE dnd.branch_ability (
    branch_id INTEGER NOT NULL REFERENCES dnd.branch(id) ON DELETE CASCADE,
    ability_id INTEGER NOT NULL REFERENCES dnd.ability(id) ON DELETE CASCADE,
    required_branch_lvl INTEGER NOT NULL CHECK (required_branch_lvl > 0),
    required_points INTEGER NOT NULL CHECK (required_points >= 0),
    PRIMARY KEY (branch_id, ability_id, required_branch_lvl)
);

-- Эффекты (категории и сами эффекты, только для ручного наложения мастером)
CREATE TABLE dnd.effect_category (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE dnd.effect (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    effect_category_id INTEGER NOT NULL REFERENCES dnd.effect_category(id),
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

-- Предметы (описание содержит урон, защиту, свойства)
CREATE TABLE dnd.item (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_category_id INTEGER NOT NULL REFERENCES dnd.item_category(id),
    name VARCHAR(100) NOT NULL UNIQUE,
    price VARCHAR(100),
    weight DECIMAL,
    max_durability INTEGER,
    current_durability INTEGER,
    description TEXT
);

-- Инвентарь и экипировка (без проверки типов, можно надеть что угодно)
CREATE TABLE dnd.inventory_item (
    item_id INTEGER NOT NULL REFERENCES dnd.item(id) ON DELETE CASCADE,
    inventory_id INTEGER NOT NULL REFERENCES dnd.inventory(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    PRIMARY KEY (item_id, inventory_id)
);

-- Персонажи
CREATE TABLE dnd.char (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES dnd."user"(id) ON DELETE CASCADE,
    species_id INTEGER NOT NULL REFERENCES dnd.species(id),    
    inventory_id INTEGER NOT NULL REFERENCES dnd.inventory(id),
    full_name VARCHAR(100) NOT NULL,
    age INTEGER CHECK (age >= 0),
    free_points INTEGER CHECK (free_points >= 0),
    lvl INTEGER CHECK (lvl > 0)
);

CREATE TABLE dnd.char_class (
    class_id INTEGER REFERENCES dnd.class(id) ON DELETE CASCADE,
    char_id INTEGER REFERENCES dnd.char(id) ON DELETE CASCADE,
    lvl INTEGER NOT NULL CHECK (lvl > 0),
    PRIMARY KEY (class_id, char_id)
);

CREATE TABLE dnd.char_branch (
    branch_id INTEGER REFERENCES dnd.branch(id) ON DELETE CASCADE,
    char_id INTEGER REFERENCES dnd.char(id) ON DELETE CASCADE,
    invested_points INTEGER CHECK(invested_points >= 0),
    current_lvl INTEGER NOT NULL DEFAULT 0 CHECK (current_lvl >= 0),
    PRIMARY KEY (branch_id, char_id)
);

CREATE TABLE dnd.char_notes (
    note_id INTEGER REFERENCES dnd.note(id) ON DELETE CASCADE,
    char_id INTEGER REFERENCES dnd.char(id) ON DELETE CASCADE,
    PRIMARY KEY (note_id, char_id)
);

CREATE TABLE dnd.effect_char (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    char_id INTEGER NOT NULL REFERENCES dnd.char(id) ON DELETE CASCADE,
    effect_id INTEGER NOT NULL REFERENCES dnd.effect(id) ON DELETE CASCADE,
    is_temporary BOOLEAN NOT NULL DEFAULT false,
    UNIQUE (char_id, effect_id)
);

CREATE TABLE dnd.stat_char (
    stat_id INTEGER NOT NULL REFERENCES dnd.stat(id) ON DELETE CASCADE,
    char_id INTEGER NOT NULL REFERENCES dnd.char(id) ON DELETE CASCADE,
    value INTEGER NOT NULL CHECK(value > 0),
    PRIMARY KEY (stat_id, char_id)
);

CREATE TABLE dnd.pool_char (
    pool_id INTEGER NOT NULL REFERENCES dnd.pool(id) ON DELETE CASCADE,
    char_id INTEGER NOT NULL REFERENCES dnd.char(id) ON DELETE CASCADE,
    value INTEGER NOT NULL CHECK (value > 0),
    coefficient DECIMAL NOT NULL DEFAULT 1.0,
    current_value INTEGER NOT NULL CHECK (current_value >= 0),
    PRIMARY KEY (pool_id, char_id)
);

-- Только стоимость способностей
CREATE TABLE dnd.ability_cost (
    ability_id INTEGER NOT NULL REFERENCES dnd.ability(id) ON DELETE CASCADE,
    pool_id INTEGER NOT NULL REFERENCES dnd.pool(id) ON DELETE CASCADE,
    cost INTEGER NOT NULL CHECK (cost > 0),
    PRIMARY KEY (ability_id, pool_id)
);

-- Изученные способности персонажа
CREATE TABLE dnd.ability_char (
    ability_id INTEGER NOT NULL REFERENCES dnd.ability(id) ON DELETE CASCADE,
    char_id INTEGER NOT NULL REFERENCES dnd.char(id) ON DELETE CASCADE,
    PRIMARY KEY (ability_id, char_id)
);

-- Экипировка (без проверки типа)
CREATE TABLE dnd.equipped_item (
    item_id INTEGER NOT NULL REFERENCES dnd.item(id) ON DELETE CASCADE,
    char_id INTEGER NOT NULL REFERENCES dnd.char(id) ON DELETE CASCADE,
    gear_slot_id INTEGER NOT NULL REFERENCES dnd.gear_slot(id) ON DELETE CASCADE,
    PRIMARY KEY (char_id, gear_slot_id)
);

-- Слоты экипировки (упрощённо, без gear_type)
CREATE TABLE dnd.gear_slot (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE dnd.branch_level (
    branch_id INTEGER NOT NULL REFERENCES dnd.branch(id) ON DELETE CASCADE,
    lvl INTEGER NOT NULL CHECK (lvl > 0),
    required_points INTEGER NOT NULL CHECK (required_points >= 0),
    PRIMARY KEY (branch_id, lvl)
);